GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/fbdc162b-7682-4e2e-a360-60dc24394868

###

POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}
###